os: linux
language: android
before_install:
- nvm install 6
- node --version
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
install:
- yarn install
jdk: oraclejdk8
sudo: required
cache: true
# android:
#   components:
#     - platform-tools
#     - tools
#     - build-tools-26.0.3
#     - android-21
#     - android-26
#     - sys-img-armeabi-v7a-android-21
#     - extra-android-m2repository
#     - extra-google-m2repository
#     - extra-google-google_play_services
script: 
- npm run ci 
- cd android && ./gradlew assembleRelease